apiVersion: v1
kind: Secret
metadata:
  name: flask-api-secret
  namespace: devsecops
type: Opaque
stringData:
# Demo purpose only - do not store real secrets in Git  
  APP_SECRET: "dummy-secret-value"
