name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
    # Évite de lancer le workflow si seuls ces fichiers sont modifiés
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

    # 1. ------Static Application Security Testing (SAST)---- 
    # Scan du code source Python pour vulnerabilités avant le build en utilisant  Bandit.
    # Reference: https://github.com/PyCQA/bandit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Python Security Scan (Bandit)
        run: |
          pip install bandit
          bandit -r app/ -ll
      

      # 2. ------ IaC scan -------
      # scan de  mauvaises configurations de sécurité dans le manifest kub en utilisant Checkov.
      # Documentation: https://github.com/bridgecrewio/checkov-action

      - name: Scan K8s Manifests (Checkov)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: k8s/
          framework: kubernetes
          # temporaire pour tests continue le pipeline même si detection
          soft_fail: true

      # 3. --- Docker Buildx ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. ---- Build image localement pour scan (sans push) ---
      - name: Build local image for scanning
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile
          load: true # Exports the build result to the local Docker image store
          tags: oelmaamar/flask-api:local-scan

      # 5. --- Scan avec Trivy  ---
      # Scan de l'image Docker avec Trivy pour détecter les CVE critiques
      # Documentation: https://github.com/aquasecurity/trivy-action

      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: oelmaamar/flask-api:local-scan
          exit-code: '1' #  Arrête le pipeline si une cve critique est détecté
          severity: 'CRITICAL'

      # 6. ---- Login sur DockerHub & Push ---
      - name: Login to DockerHub
        if: github.event_name != 'pull_request' # login que si ce n'est pas une PR
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push docker image 
        if: github.event_name != 'pull_request' 
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            IMAGE_TAG="$GITHUB_REF_NAME"
          else
            IMAGE_TAG="latest"
          fi

          docker tag flask-api:local-scan oelmaamar/flask-api:$IMAGE_TAG
          docker push oelmaamar/flask-api:$IMAGE_TAG
          
      # 7. --- DEPLOY (sur k8s cluster local ) ---       
  deploy: 
    needs: build-and-scan
    runs-on: self-hosted
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Deploy to local Cluster
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            IMAGE_TAG="$GITHUB_REF_NAME"
          else
            IMAGE_TAG="latest"
          fi

          kubectl apply -f k8s/

          kubectl set image deployment/flask-api flask-api=oelmaamar/flask-api:$IMAGE_TAG -n devsecops

          kubectl rollout status deployment/flask-api -n devsecops --timeout=120s
